export const mockUser = {
  id: 1,
  name: 'QA Tester',
  email: 'qa.tester@example.com',
  picture: '',
  profilePictureUrl: '',
  googleId: 'google-qa-tester',
  success: true,
  message: 'User retrieved successfully',
  data: {
    id: 1,
    name: 'QA Tester',
    email: 'qa.tester@example.com',
  },
};

export const sampleEmails = [
  {
    id: 'msg-inbox-1',
    sender: { name: 'Jane Cooper', email: 'jane.cooper@example.com' },
    recipients: ['qa.tester@example.com'],
    subject: 'Q3 Planning Notes',
    snippet: 'Please review the attached agenda for Q3 planning.',
    timestamp: '10:45 AM',
    fullDate: 'Today at 10:45 AM',
    isRead: false,
    isStarred: true,
    isImportant: true,
    folder: 'inbox',
    labels: ['Work', 'Urgent'],
    thread: [
      {
        id: 'thread-1',
        sender: { name: 'Jane Cooper', email: 'jane.cooper@example.com' },
        recipients: ['qa.tester@example.com'],
        timestamp: '10:45 AM',
        fullDate: 'Today at 10:45 AM',
        body: 'Please review the attached agenda for Q3 planning. We need a decision by Friday.',
      },
    ],
    needsResponse: true,
  },
  {
    id: 'msg-inbox-2',
    sender: { name: 'John Miller', email: 'john.miller@example.com' },
    recipients: ['qa.tester@example.com'],
    subject: 'Lunch next week',
    snippet: 'Are you free for lunch on Tuesday?',
    timestamp: 'Yesterday',
    fullDate: 'Yesterday at 3:12 PM',
    isRead: true,
    isStarred: false,
    isImportant: false,
    folder: 'inbox',
    labels: ['Personal'],
    thread: [
      {
        id: 'thread-2',
        sender: { name: 'John Miller', email: 'john.miller@example.com' },
        recipients: ['qa.tester@example.com'],
        timestamp: 'Yesterday',
        fullDate: 'Yesterday at 3:12 PM',
        body: 'Are you free for lunch on Tuesday?',
      },
    ],
  },
  {
    id: 'msg-promo-1',
    sender: { name: 'Store Deals', email: 'deals@promo.example.com' },
    recipients: ['qa.tester@example.com'],
    subject: '50% off this weekend',
    snippet: 'Limited-time promotional offer inside.',
    timestamp: 'Mon',
    fullDate: 'Monday at 9:00 AM',
    isRead: true,
    isStarred: false,
    isImportant: false,
    folder: 'inbox',
    labels: ['Promotions'],
    thread: [
      {
        id: 'thread-3',
        sender: { name: 'Store Deals', email: 'deals@promo.example.com' },
        recipients: ['qa.tester@example.com'],
        timestamp: 'Mon',
        fullDate: 'Monday at 9:00 AM',
        body: 'Limited-time promotional offer inside.',
      },
    ],
  },
  {
    id: 'msg-sent-1',
    sender: { name: 'QA Tester', email: 'qa.tester@example.com' },
    recipients: ['jane.cooper@example.com'],
    subject: 'Re: Q3 Planning Notes',
    snippet: 'Thanks, I will review today.',
    timestamp: '9:10 AM',
    fullDate: 'Today at 9:10 AM',
    isRead: true,
    isStarred: false,
    isImportant: false,
    folder: 'sent',
    labels: ['Work'],
    thread: [
      {
        id: 'thread-4',
        sender: { name: 'QA Tester', email: 'qa.tester@example.com' },
        recipients: ['jane.cooper@example.com'],
        timestamp: '9:10 AM',
        fullDate: 'Today at 9:10 AM',
        body: 'Thanks, I will review today.',
      },
    ],
  },
];
